routes:
  /users: user/index
  '/users/{username}': user/profile
  /account: user/account
  /login: auth/login
  /register: auth/register
  /forgot-password: auth/password-forgot
  /reset-password: auth/password-reset
  /sitemap:
    template: sitemap
    layout: sitemap
    content_type: xml
collections:
  works: '/work/{slug}'
  people: 'studio/{slug}'